# datasource_monitor.yaml
name: "datasource_monitor"
source:
  type: "kafka"
  config:
    connection:
      bootstrap: ${KAFKA_BOOTSTRAP_SERVER:-localhost:9092}
      schema_registry_url: ${SCHEMA_REGISTRY_URL:-http://localhost:8081}
    topic_routes:
      mcl: ${METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME:-DataHubMetadataChangeLog_Versioned_v1}
      pe: ${PLATFORM_EVENT_TOPIC_NAME:-DataHubPlatformEvent_v1}
action:
  type: "wap_actions.datasource_monitor:DatasourceMonitorAction"
  config:
    output_json: ${CUD_OUTPUT_JSON:-true}
    access_token_url: ${CI_ACCESS_TOKEN_URL:-https://idbrokerbts.webex.com/idb/oauth2/v1/access_token}
    username: ${CI_ACCESS_TOKEN_USER:-user}
    password: ${CI_ACCESS_TOKEN_PASS:-pass}
    bearer_token_url: ${CI_BEARER_TOKEN_URL:-https://idbrokerbts.webex.com/idb/token/6078fba4-49d9-4291-9f7b-80116aab6974/v2/actions/GetBearerToken/invoke}
    machine_account_name: ${CI_MACHINE_NAME:-CTGWAP-DATAHUB}
    machine_account_pass: ${CI_MACHINE_PASS:-pass}
    datasource_refresh_api: ${CUD_REFRESH_API:-http://10.29.41.71:8021/api/v1/data-sources/refresh}
